#
# BTstack example 'hid_host_demo' for ESP32 port
#
# Generated by /home/minatsu/esp/btstack/port/esp32
# On Tue Oct  9 23:12:44 2018

PROJECT_NAME := esp32_wiiremote

include $(IDF_PATH)/make/project.mk
